"""AutoLISP probe generation for future read-only viewport/selection reads."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from cad_chat_bridge.security.paths import ensure_safe_artifact_path


class ViewportReadMode(str, Enum):
    """Supported read sources for generated viewport probes."""

    CURRENT_VIEW = "current_view"
    SELECTION = "selection"
    WINDOW = "window"


@dataclass(frozen=True)
class ViewWindow:
    """World-coordinate rectangular read range."""

    min_x: float
    min_y: float
    max_x: float
    max_y: float

    @classmethod
    def from_points(cls, first: tuple[float, float], second: tuple[float, float]) -> "ViewWindow":
        x1, y1 = float(first[0]), float(first[1])
        x2, y2 = float(second[0]), float(second[1])
        return cls(min(x1, x2), min(y1, y2), max(x1, x2), max(y1, y2))

    def to_dict(self) -> dict[str, float]:
        return {
            "min_x": self.min_x,
            "min_y": self.min_y,
            "max_x": self.max_x,
            "max_y": self.max_y,
        }


def escape_lisp_string(value: str | Path) -> str:
    """Escape a string for a quoted AutoLISP string literal."""

    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def _entity_types(types: str | list[str] | tuple[str, ...] | None) -> tuple[str, ...]:
    if types is None:
        return ()
    if isinstance(types, str):
        raw = types.split(",")
    else:
        raw = types
    return tuple(item.strip().upper() for item in raw if item and item.strip())


def build_viewport_probe(
    *,
    mode: str | ViewportReadMode,
    layer_filter: str = "*",
    entity_types: str | list[str] | tuple[str, ...] | None = None,
    window: ViewWindow | None = None,
    output_path: str | Path | None = None,
    artifact_root: str | Path | None = None,
) -> dict[str, Any]:
    """Build a conservative AutoLISP probe script without executing it.

    If ``output_path`` is supplied it must be inside the controlled artifact root.
    The MVP does not run this script through COM; it only prepares and tests the
    read-only probe for a later execution tool.
    """

    read_mode = mode if isinstance(mode, ViewportReadMode) else ViewportReadMode(str(mode))
    if read_mode == ViewportReadMode.WINDOW and window is None:
        raise ValueError("window mode requires a ViewWindow.")

    safe_output = None
    if output_path is not None:
        safe_output = ensure_safe_artifact_path(output_path, root=artifact_root)

    type_filter = _entity_types(entity_types)
    request = {
        "mode": read_mode.value,
        "layer_filter": layer_filter,
        "entity_types": list(type_filter),
        "window": window.to_dict() if window else None,
        "output_path": str(safe_output) if safe_output else None,
    }

    filter_expr = _selection_filter_expr(layer_filter=layer_filter, entity_types=type_filter)
    selection_expr = _selection_expr(read_mode, filter_expr, window)
    output_expr = _output_expr(safe_output)

    script = f"""; Generated by CAD Chat Bridge viewport probe.
(defun ccb:json-escape (s / out i ch)
  (setq out "" i 1 s (if s s ""))
  (while (<= i (strlen s))
    (setq ch (substr s i 1))
    (cond
      ((= ch "\\\\") (setq out (strcat out "\\\\\\\\")))
      ((= ch "\\"") (setq out (strcat out "\\\\\\"")))
      (T (setq out (strcat out ch)))
    )
    (setq i (1+ i))
  )
  out
)

(defun ccb:num (v)
  (if v (rtos v 2 8) "0")
)

(defun ccb:pt-json (p)
  (strcat "{{\\"x\\":" (ccb:num (car p)) ",\\"y\\":" (ccb:num (cadr p)) ",\\"z\\":" (ccb:num (if (caddr p) (caddr p) 0)) "}}")
)

(defun ccb:assoc-json (key value)
  (strcat "\\"" key "\\":\\"" (ccb:json-escape value) "\\"")
)

(defun ccb:entity-json (ename / data typ layer handle p10 p11 radius text)
  (setq data (entget ename))
  (setq typ (cdr (assoc 0 data)))
  (setq layer (cdr (assoc 8 data)))
  (setq handle (cdr (assoc 5 data)))
  (setq p10 (cdr (assoc 10 data)))
  (setq p11 (cdr (assoc 11 data)))
  (setq radius (cdr (assoc 40 data)))
  (setq text (cdr (assoc 1 data)))
  (strcat
    "{{"
    (ccb:assoc-json "entity_type" typ) ","
    (ccb:assoc-json "layer" layer) ","
    (ccb:assoc-json "handle" handle) ","
    "\\"geometry\\":{{"
      (if p10 (strcat "\\"point10\\":" (ccb:pt-json p10)) "\\"point10\\":null")
      (if p11 (strcat ",\\"point11\\":" (ccb:pt-json p11)) "")
    "}},"
    "\\"properties\\":{{"
      (if radius (strcat "\\"radius\\":" (ccb:num radius)) "\\"radius\\":null")
      (if text (strcat ",\\"content\\":\\"" (ccb:json-escape text) "\\"") "")
    "}}"
    "}}"
  )
)

(defun ccb:ss-json (ss / i parts)
  (setq i 0 parts "[")
  (if ss
    (while (< i (sslength ss))
      (setq parts (strcat parts (if (> i 0) "," "") (ccb:entity-json (ssname ss i))))
      (setq i (1+ i))
    )
  )
  (strcat parts "]")
)

(defun ccb:current-view-window (/ ctr h scr w)
  (setq ctr (getvar "VIEWCTR"))
  (setq h (getvar "VIEWSIZE"))
  (setq scr (getvar "SCREENSIZE"))
  (setq w (* h (/ (float (car scr)) (float (cadr scr)))))
  (list
    (list (- (car ctr) (/ w 2.0)) (- (cadr ctr) (/ h 2.0)) 0.0)
    (list (+ (car ctr) (/ w 2.0)) (+ (cadr ctr) (/ h 2.0)) 0.0)
  )
)

(defun ccb:viewport-probe (/ ss win payload fp)
  (setq ss {selection_expr})
  (setq payload
    (strcat
      "{{\\"source\\":\\"{read_mode.value}\\","
      "\\"selection_count\\":" (itoa (if ss (sslength ss) 0)) ","
      "\\"entities\\":" (ccb:ss-json ss)
      "}}"
    )
  )
  {output_expr}
  payload
)

(ccb:viewport-probe)
(princ)
"""

    return {"success": True, "request": request, "lisp": script}


def _selection_filter_expr(*, layer_filter: str, entity_types: tuple[str, ...]) -> str:
    parts: list[str] = []
    if layer_filter != "*":
        parts.append(f'(8 . "{escape_lisp_string(layer_filter)}")')
    if entity_types:
        parts.append(f'(0 . "{escape_lisp_string(",".join(entity_types))}")')
    if not parts:
        return "nil"
    return "'(" + " ".join(parts) + ")"


def _selection_expr(
    mode: ViewportReadMode, filter_expr: str, window: ViewWindow | None
) -> str:
    filter_suffix = f" {filter_expr}" if filter_expr != "nil" else ""
    if mode == ViewportReadMode.SELECTION:
        return f'(ssget "_I"{filter_suffix})'
    if mode == ViewportReadMode.WINDOW:
        if window is None:
            raise ValueError("window mode requires a ViewWindow.")
        p1 = f"'({window.min_x} {window.min_y} 0.0)"
        p2 = f"'({window.max_x} {window.max_y} 0.0)"
        return f'(ssget "_C" {p1} {p2}{filter_suffix})'
    return f'(progn (setq win (ccb:current-view-window)) (ssget "_C" (car win) (cadr win){filter_suffix}))'


def _output_expr(output_path: Path | None) -> str:
    if output_path is None:
        return "(princ payload)"
    path = escape_lisp_string(output_path.as_posix())
    return f'(setq fp (open "{path}" "w"))\n  (write-line payload fp)\n  (close fp)'
